//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemZZ_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class DomZdravlja
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DomZdravlja()
        {
            this.Prevoz = new HashSet<Prevoz>();
            this.ZdravstenaZastita = new HashSet<ZdravstenaZastita>();
        }
    
        public int ID_DZ { get; set; }
        public string AdresaDZ { get; set; }
        public string BrTelDZ { get; set; }
        public string BrZap { get; set; }
        public string DirDZ { get; set; }
    
        public virtual UstanovaAP UstanovaAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prevoz> Prevoz { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZdravstenaZastita> ZdravstenaZastita { get; set; }
    }
}
