//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemZZ_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prevoz
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prevoz()
        {
            this.DomZdravlja = new HashSet<DomZdravlja>();
        }
    
        public int ID_V { get; set; }
        public string ImeVozaca { get; set; }
        public string MarkaVoz { get; set; }
        public string BrMesta { get; set; }
        public string TipPrevoza { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DomZdravlja> DomZdravlja { get; set; }
    }
}
