//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemZZ_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZdravstveniRadnik
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZdravstveniRadnik()
        {
            this.ZdravstenaZastita = new HashSet<ZdravstenaZastita>();
        }
    
        public int ID_ZR { get; set; }
        public string TipZR { get; set; }
        public string ImeZR { get; set; }
        public string PrezimeZR { get; set; }
        public string GodZR { get; set; }
        public string OdeljenjeZR { get; set; }
        public string TelZR { get; set; }
        public string GodZapos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZdravstenaZastita> ZdravstenaZastita { get; set; }
    }
}
