//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemZZ_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZdravstvenaUstanova
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZdravstvenaUstanova()
        {
            this.UstanovaAP = new HashSet<UstanovaAP>();
        }
    
        public int ID_ZU { get; set; }
        public string NazivZU { get; set; }
        public string AdresaZU { get; set; }
        public string BrTelZU { get; set; }
        public int SistemZdravstveneZastiteID_SZZ { get; set; }
    
        public virtual SistemZdravstveneZastite SistemZdravstveneZastite { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UstanovaAP> UstanovaAP { get; set; }
    }
}
